### ISSUE TITLE
AttributeError after upgrading 3.2.2 to 3.4.0

### ISSUE THREAD

**Issue by rossi-fi** [Iapetus-11/aio-mc-rcon#11]
I can use 3.2.2 but I get the following error with 3.4.0:

```
site-packages/aiomcrcon/__init__.py", line 5, in <module>
    __version__ = importlib.metadata.version("aio-mc-rcon")
                  ^^^^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'metadata'
```

Python 3.12.9. Appears to work with `import importlib.metadata` instead [here](https://github.com/Iapetus-11/aio-mc-rcon/blob/272091b0ed3bc35bfb1bd663d99289ea074c3e4c/aiomcrcon/__init__.py#L1).

**Comment by Iapetus-11** [comment]
Looking into this now, sorry for the problems :/

**Comment by Iapetus-11** [comment]
Just released 3.4.1. Hope it works. Thank you for the report, i really appreciate it! ❤

**Comment by rossi-fi** [comment]
Many thanks!
